// Training programs data - reusable across the application
export const trainingProgramsData = {
     "python-data-science": {
          id: 1,
          title: "Python & Data Science Bootcamp",
          description:
               "Comprehensive training program for organizations to develop Python programming and data science capabilities. Perfect for teams looking to build data-driven solutions.",
          longDescription:
               "This intensive training program is designed for organizations that want to equip their teams with Python programming and data science skills. The program covers everything from basic Python syntax to advanced data analysis, machine learning, and real-world project implementation. Our expert-led approach ensures practical, hands-on learning that can be immediately applied in your organization's projects.",
          duration: "8 weeks",
          level: "Beginner to Intermediate",
          price: "Custom Pricing",
          originalPrice: null,
          rating: 4.9,
          organizationsServed: 45,
          image: "https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=600&q=80",
          category: "Python & Data Science",
          organizationType: "All Organizations",
          participants: "15-25 professionals",
          format: "Hybrid (Online + In-Person)",
          instructor: {
               name: "Roshan KC",
               bio: "Senior Data Scientist and Training Director with 12+ years of experience in Python development, data science, and organizational training.",
               image: "https://images.unsplash.com/photo-1494790108755-2616b612b786?auto=format&fit=crop&w=150&q=80",
          },
          features: [
               "8 weeks of comprehensive training",
               "Customized curriculum for your organization",
               "Hands-on project development",
               "Industry expert instructors",
               "Certificate of completion",
               "Post-training support and consultation",
               "Flexible scheduling options",
               "Real-world case studies",
          ],
          curriculum: [
               {
                    week: 1,
                    title: "Python Fundamentals for Business",
                    topics: [
                         "Python setup and environment",
                         "Basic syntax and data types",
                         "Control structures",
                         "Functions and modules",
                    ],
               },
               {
                    week: 2,
                    title: "Data Manipulation & Analysis",
                    topics: [
                         "Pandas for data analysis",
                         "NumPy for numerical computing",
                         "Data cleaning and preprocessing",
                         "Exploratory data analysis",
                    ],
               },
               {
                    week: 3,
                    title: "Data Visualization",
                    topics: [
                         "Matplotlib and Seaborn",
                         "Interactive visualizations",
                         "Dashboard creation",
                         "Storytelling with data",
                    ],
               },
               {
                    week: 4,
                    title: "Statistical Analysis",
                    topics: [
                         "Descriptive statistics",
                         "Hypothesis testing",
                         "Correlation analysis",
                         "Statistical modeling",
                    ],
               },
               {
                    week: 5,
                    title: "Machine Learning Basics",
                    topics: [
                         "Supervised learning",
                         "Classification algorithms",
                         "Regression models",
                         "Model evaluation",
                    ],
               },
               {
                    week: 6,
                    title: "Advanced ML & AI",
                    topics: [
                         "Unsupervised learning",
                         "Neural networks",
                         "Deep learning basics",
                         "AI applications",
                    ],
               },
               {
                    week: 7,
                    title: "Real-World Projects",
                    topics: [
                         "Project planning",
                         "Data pipeline development",
                         "Model deployment",
                         "Performance optimization",
                    ],
               },
               {
                    week: 8,
                    title: "Implementation & Strategy",
                    topics: [
                         "Organizational integration",
                         "Best practices",
                         "Team collaboration",
                         "Future roadmap planning",
                    ],
               },
          ],
          prerequisites: [
               "Basic computer literacy",
               "No prior programming experience required",
               "Team commitment to learning",
               "Organizational support for implementation",
          ],
          outcomes: [
               "Develop Python programming expertise across your team",
               "Build data-driven decision-making capabilities",
               "Implement machine learning solutions for business problems",
               "Create automated data processing pipelines",
               "Establish data science best practices in your organization",
               "Prepare for advanced AI and ML initiatives",
          ],
          targetOrganizations: [
               "Corporations",
               "Universities",
               "Government Agencies",
               "Non-Profit Organizations",
          ],
          deliveryOptions: [
               "In-Person Training",
               "Online Sessions",
               "Hybrid Approach",
               "Custom Schedule",
          ],
     },
     "ai-machine-learning": {
          id: 2,
          title: "AI & Machine Learning Masterclass",
          description:
               "Advanced training program for organizations to implement cutting-edge AI and machine learning solutions. Transform your business with intelligent automation and predictive analytics.",
          longDescription:
               "This comprehensive AI and machine learning training program is designed for organizations ready to embrace the future of technology. From neural networks to natural language processing, our expert-led program covers the most advanced AI technologies and their practical business applications.",
          duration: "10 weeks",
          level: "Intermediate to Advanced",
          price: "Custom Pricing",
          originalPrice: null,
          rating: 4.8,
          organizationsServed: 32,
          image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=600&q=80",
          category: "AI & Machine Learning",
          organizationType: "Corporations & Universities",
          participants: "10-20 professionals",
          format: "Hybrid (Online + In-Person)",
          instructor: {
               name: "Roshan KC",
               bio: "AI Research Director and Machine Learning Expert with 15+ years of experience in artificial intelligence, deep learning, and enterprise AI solutions.",
               image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
          },
          features: [
               "10 weeks of intensive AI training",
               "Customized AI strategy development",
               "Hands-on deep learning projects",
               "Industry-leading AI experts",
               "Certificate of completion",
               "Post-training AI consultation",
               "Flexible scheduling options",
               "Real-world AI case studies",
          ],
          curriculum: [
               {
                    week: 1,
                    title: "AI Fundamentals & Strategy",
                    topics: [
                         "AI landscape and business applications",
                         "Machine learning vs deep learning",
                         "AI strategy development",
                         "Ethical AI considerations",
                    ],
               },
               {
                    week: 2,
                    title: "Advanced Machine Learning",
                    topics: [
                         "Supervised learning algorithms",
                         "Unsupervised learning techniques",
                         "Model optimization and tuning",
                         "Performance evaluation metrics",
                    ],
               },
               {
                    week: 3,
                    title: "Neural Networks & Deep Learning",
                    topics: [
                         "Neural network architectures",
                         "Backpropagation and optimization",
                         "Convolutional Neural Networks (CNN)",
                         "Recurrent Neural Networks (RNN)",
                    ],
               },
               {
                    week: 4,
                    title: "Natural Language Processing",
                    topics: [
                         "Text preprocessing and analysis",
                         "Sentiment analysis",
                         "Language models and transformers",
                         "Chatbot development",
                    ],
               },
               {
                    week: 5,
                    title: "Computer Vision",
                    topics: [
                         "Image processing fundamentals",
                         "Object detection and recognition",
                         "Image segmentation",
                         "Video analysis",
                    ],
               },
               {
                    week: 6,
                    title: "AI for Business Applications",
                    topics: [
                         "Predictive analytics",
                         "Recommendation systems",
                         "Anomaly detection",
                         "Process automation",
                    ],
               },
               {
                    week: 7,
                    title: "AI Deployment & MLOps",
                    topics: [
                         "Model deployment strategies",
                         "MLOps best practices",
                         "Model monitoring and maintenance",
                         "Scalability considerations",
                    ],
               },
               {
                    week: 8,
                    title: "Advanced AI Technologies",
                    topics: [
                         "Generative AI and GANs",
                         "Reinforcement learning",
                         "Edge AI and IoT",
                         "AI ethics and governance",
                    ],
               },
               {
                    week: 9,
                    title: "AI Project Implementation",
                    topics: [
                         "AI project planning and scoping",
                         "Team collaboration and workflows",
                         "Risk assessment and mitigation",
                         "Success metrics and KPIs",
                    ],
               },
               {
                    week: 10,
                    title: "Future of AI & Strategy",
                    topics: [
                         "Emerging AI technologies",
                         "AI roadmap development",
                         "Competitive advantage strategies",
                         "Long-term AI vision",
                    ],
               },
          ],
          prerequisites: [
               "Basic programming knowledge (Python preferred)",
               "Understanding of statistics and mathematics",
               "Organizational commitment to AI transformation",
               "Dedicated team for AI implementation",
          ],
          outcomes: [
               "Implement advanced AI and ML solutions in your organization",
               "Develop custom AI models for business problems",
               "Build scalable AI infrastructure and workflows",
               "Create AI-driven business strategies and roadmaps",
               "Establish AI governance and ethical frameworks",
               "Lead AI transformation initiatives",
          ],
          targetOrganizations: [
               "Corporations",
               "Universities",
               "Technology Companies",
               "Research Institutions",
          ],
          deliveryOptions: [
               "In-Person Training",
               "Online Sessions",
               "Hybrid Approach",
               "Custom Schedule",
          ],
     },
     "cloud-devops": {
          id: 3,
          title: "Cloud Computing & DevOps Bootcamp",
          description:
               "Comprehensive training program for organizations to master cloud platforms and DevOps practices. Build scalable, reliable, and efficient infrastructure.",
          longDescription:
               "This intensive cloud computing and DevOps training program equips organizations with the skills to build, deploy, and maintain modern cloud-native applications. From AWS and Azure to Kubernetes and CI/CD pipelines, our program covers everything needed for successful cloud transformation.",
          duration: "6 weeks",
          level: "Intermediate",
          price: "Custom Pricing",
          originalPrice: null,
          rating: 4.7,
          organizationsServed: 38,
          image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=600&q=80",
          category: "Cloud & DevOps",
          organizationType: "All Organizations",
          participants: "12-20 professionals",
          format: "Hybrid (Online + In-Person)",
          instructor: {
               name: "Roshan KC",
               bio: "Cloud Architecture Expert and DevOps Engineer with 10+ years of experience in cloud platforms, containerization, and infrastructure automation.",
               image: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=150&q=80",
          },
          features: [
               "6 weeks of comprehensive cloud training",
               "Multi-cloud platform coverage",
               "Hands-on infrastructure projects",
               "Industry expert instructors",
               "Certificate of completion",
               "Post-training cloud consultation",
               "Flexible scheduling options",
               "Real-world cloud case studies",
          ],
          curriculum: [
               {
                    week: 1,
                    title: "Cloud Fundamentals & Strategy",
                    topics: [
                         "Cloud computing models (IaaS, PaaS, SaaS)",
                         "Cloud service providers overview",
                         "Cloud migration strategies",
                         "Cost optimization and governance",
                    ],
               },
               {
                    week: 2,
                    title: "AWS & Azure Deep Dive",
                    topics: [
                         "Core AWS services and architecture",
                         "Azure services and integration",
                         "Multi-cloud strategies",
                         "Security and compliance",
                    ],
               },
               {
                    week: 3,
                    title: "Containerization & Orchestration",
                    topics: [
                         "Docker containerization",
                         "Kubernetes orchestration",
                         "Container security",
                         "Microservices architecture",
                    ],
               },
               {
                    week: 4,
                    title: "DevOps Practices & Tools",
                    topics: [
                         "CI/CD pipeline development",
                         "Infrastructure as Code (IaC)",
                         "Configuration management",
                         "Monitoring and logging",
                    ],
               },
               {
                    week: 5,
                    title: "Advanced Cloud Services",
                    topics: [
                         "Serverless computing",
                         "Cloud-native databases",
                         "API management",
                         "Edge computing",
                    ],
               },
               {
                    week: 6,
                    title: "Cloud Security & Operations",
                    topics: [
                         "Cloud security best practices",
                         "Identity and access management",
                         "Disaster recovery planning",
                         "Performance optimization",
                    ],
               },
          ],
          prerequisites: [
               "Basic IT infrastructure knowledge",
               "Understanding of networking concepts",
               "Organizational cloud strategy alignment",
               "Technical team availability",
          ],
          outcomes: [
               "Design and implement cloud-native architectures",
               "Build automated CI/CD pipelines",
               "Manage containerized applications with Kubernetes",
               "Implement cloud security and compliance measures",
               "Optimize cloud costs and performance",
               "Establish DevOps culture and practices",
          ],
          targetOrganizations: [
               "Corporations",
               "Technology Companies",
               "Government Agencies",
               "Educational Institutions",
          ],
          deliveryOptions: [
               "In-Person Training",
               "Online Sessions",
               "Hybrid Approach",
               "Custom Schedule",
          ],
     },
     cybersecurity: {
          id: 4,
          title: "Cybersecurity & Information Security",
          description:
               "Comprehensive cybersecurity training program for organizations to protect against evolving threats and ensure data security compliance.",
          longDescription:
               "This intensive cybersecurity training program prepares organizations to defend against modern cyber threats while ensuring compliance with security regulations. From threat detection to incident response, our program covers all aspects of organizational cybersecurity.",
          duration: "8 weeks",
          level: "Intermediate",
          price: "Custom Pricing",
          originalPrice: null,
          rating: 4.9,
          organizationsServed: 28,
          image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?auto=format&fit=crop&w=600&q=80",
          category: "Cybersecurity",
          organizationType: "All Organizations",
          participants: "10-15 professionals",
          format: "Hybrid (Online + In-Person)",
          instructor: {
               name: "Elvik Sharma",
               bio: "Cybersecurity Expert and Information Security Consultant with 12+ years of experience in threat intelligence, incident response, and security architecture.",
               image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80",
          },
          features: [
               "8 weeks of comprehensive security training",
               "Threat simulation and response",
               "Hands-on security projects",
               "Industry expert instructors",
               "Certificate of completion",
               "Post-training security consultation",
               "Flexible scheduling options",
               "Real-world security case studies",
          ],
          curriculum: [
               {
                    week: 1,
                    title: "Cybersecurity Fundamentals",
                    topics: [
                         "Security principles and frameworks",
                         "Threat landscape analysis",
                         "Risk assessment methodologies",
                         "Security governance",
                    ],
               },
               {
                    week: 2,
                    title: "Network Security",
                    topics: [
                         "Network architecture security",
                         "Firewall configuration",
                         "Intrusion detection systems",
                         "VPN and remote access security",
                    ],
               },
               {
                    week: 3,
                    title: "Application Security",
                    topics: [
                         "Secure coding practices",
                         "Web application security",
                         "API security",
                         "Mobile application security",
                    ],
               },
               {
                    week: 4,
                    title: "Cloud Security",
                    topics: [
                         "Cloud security models",
                         "Identity and access management",
                         "Data protection in the cloud",
                         "Cloud compliance requirements",
                    ],
               },
               {
                    week: 5,
                    title: "Threat Detection & Response",
                    topics: [
                         "Security monitoring tools",
                         "Incident detection and analysis",
                         "Threat hunting techniques",
                         "Incident response procedures",
                    ],
               },
               {
                    week: 6,
                    title: "Data Protection & Privacy",
                    topics: [
                         "Data classification and handling",
                         "Encryption technologies",
                         "Privacy regulations (GDPR, CCPA)",
                         "Data breach response",
                    ],
               },
               {
                    week: 7,
                    title: "Security Operations",
                    topics: [
                         "Security operations center (SOC)",
                         "Vulnerability management",
                         "Penetration testing",
                         "Security awareness training",
                    ],
               },
               {
                    week: 8,
                    title: "Compliance & Governance",
                    topics: [
                         "Security compliance frameworks",
                         "Audit preparation and response",
                         "Security policy development",
                         "Business continuity planning",
                    ],
               },
          ],
          prerequisites: [
               "Basic IT infrastructure knowledge",
               "Understanding of networking concepts",
               "Organizational security commitment",
               "Compliance requirements awareness",
          ],
          outcomes: [
               "Implement comprehensive cybersecurity frameworks",
               "Detect and respond to security threats",
               "Ensure compliance with security regulations",
               "Develop security policies and procedures",
               "Conduct security assessments and audits",
               "Build security-aware organizational culture",
          ],
          targetOrganizations: [
               "Corporations",
               "Government Agencies",
               "Healthcare Organizations",
               "Financial Institutions",
          ],
          deliveryOptions: [
               "In-Person Training",
               "Online Sessions",
               "Hybrid Approach",
               "Custom Schedule",
          ],
     },
     "web-development": {
          id: 5,
          title: "Modern Web Development & Full-Stack Engineering",
          description:
               "Comprehensive training program for organizations to build modern, scalable web applications using cutting-edge technologies and best practices.",
          longDescription:
               "This intensive web development training program covers the full spectrum of modern web technologies, from frontend frameworks to backend services and deployment strategies. Our program prepares teams to build robust, scalable web applications that meet today's business demands.",
          duration: "10 weeks",
          level: "Beginner to Advanced",
          price: "Custom Pricing",
          originalPrice: null,
          rating: 4.6,
          organizationsServed: 42,
          image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=600&q=80",
          category: "Web Development",
          organizationType: "All Organizations",
          participants: "15-25 professionals",
          format: "Hybrid (Online + In-Person)",
          instructor: {
               name: "Vaskar Parajuli",
               bio: "Full-Stack Development Expert and Technical Lead with 10+ years of experience in modern web technologies, architecture design, and team leadership.",
               image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80",
          },
          features: [
               "10 weeks of comprehensive web development training",
               "Full-stack technology coverage",
               "Hands-on project development",
               "Industry expert instructors",
               "Certificate of completion",
               "Post-training development consultation",
               "Flexible scheduling options",
               "Real-world web development case studies",
          ],
          curriculum: [
               {
                    week: 1,
                    title: "Web Development Fundamentals",
                    topics: [
                         "HTML5 and CSS3 advanced features",
                         "JavaScript ES6+ and modern syntax",
                         "Responsive design principles",
                         "Web accessibility standards",
                    ],
               },
               {
                    week: 2,
                    title: "Frontend Frameworks",
                    topics: [
                         "React.js fundamentals and hooks",
                         "Vue.js and Angular basics",
                         "State management (Redux, Vuex)",
                         "Component architecture",
                    ],
               },
               {
                    week: 3,
                    title: "Backend Development",
                    topics: [
                         "Node.js and Express.js",
                         "Python with Django/Flask",
                         "Database design and modeling",
                         "RESTful API development",
                    ],
               },
               {
                    week: 4,
                    title: "Database & Data Management",
                    topics: [
                         "SQL and NoSQL databases",
                         "Database optimization",
                         "Data modeling and relationships",
                         "Caching strategies",
                    ],
               },
               {
                    week: 5,
                    title: "Modern Frontend Technologies",
                    topics: [
                         "TypeScript and type safety",
                         "CSS frameworks and preprocessors",
                         "Build tools and bundlers",
                         "Progressive Web Apps (PWA)",
                    ],
               },
               {
                    week: 6,
                    title: "API Development & Integration",
                    topics: [
                         "GraphQL API development",
                         "API authentication and security",
                         "Third-party API integration",
                         "API testing and documentation",
                    ],
               },
               {
                    week: 7,
                    title: "DevOps for Web Applications",
                    topics: [
                         "Docker containerization",
                         "CI/CD for web applications",
                         "Cloud deployment strategies",
                         "Performance monitoring",
                    ],
               },
               {
                    week: 8,
                    title: "Advanced Web Technologies",
                    topics: [
                         "Server-side rendering (SSR)",
                         "Static site generation (SSG)",
                         "WebAssembly (WASM)",
                         "Real-time applications",
                    ],
               },
               {
                    week: 9,
                    title: "Testing & Quality Assurance",
                    topics: [
                         "Unit testing and integration testing",
                         "End-to-end testing",
                         "Code quality and linting",
                         "Performance testing",
                    ],
               },
               {
                    week: 10,
                    title: "Deployment & Maintenance",
                    topics: [
                         "Production deployment strategies",
                         "Monitoring and logging",
                         "Security best practices",
                         "Maintenance and updates",
                    ],
               },
          ],
          prerequisites: [
               "Basic programming knowledge",
               "Understanding of web technologies",
               "Organizational commitment to web development",
               "Team collaboration skills",
          ],
          outcomes: [
               "Build modern, responsive web applications",
               "Develop full-stack web solutions",
               "Implement scalable web architectures",
               "Deploy and maintain web applications",
               "Follow web development best practices",
               "Lead web development projects",
          ],
          targetOrganizations: [
               "Corporations",
               "Technology Companies",
               "Digital Agencies",
               "Educational Institutions",
          ],
          deliveryOptions: [
               "In-Person Training",
               "Online Sessions",
               "Hybrid Approach",
               "Custom Schedule",
          ],
     },
     "game-development": {
          id: 6,
          title: "Game Development & Interactive Media",
          description:
               "Comprehensive training program for organizations to create engaging games and interactive applications using modern game development technologies and design principles.",
          longDescription:
               "This intensive game development training program covers the full spectrum of game creation, from concept design to deployment. Organizations will learn to build interactive experiences using Unity, Unreal Engine, and modern web technologies. Perfect for teams looking to enter the gaming industry or create interactive training simulations.",
          duration: "12 weeks",
          level: "Beginner to Advanced",
          price: "Custom Pricing",
          originalPrice: null,
          rating: 4.7,
          organizationsServed: 25,
          image: "https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=600&q=80",
          category: "Game Development",
          organizationType: "All Organizations",
          participants: "10-20 professionals",
          format: "Hybrid (Online + In-Person)",
          instructor: {
               name: "Elvik Sharma",
               bio: "Game Development Expert and Technical Director with 8+ years of experience in Unity, Unreal Engine, and interactive media development.",
               image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
          },
          features: [
               "12 weeks of comprehensive game development training",
               "Unity and Unreal Engine mastery",
               "3D modeling and animation basics",
               "Game design principles and mechanics",
               "Certificate of completion",
               "Post-training game development consultation",
               "Flexible scheduling options",
               "Real-world game development projects",
          ],
          curriculum: [
               {
                    week: 1,
                    title: "Game Development Fundamentals",
                    topics: [
                         "Game design principles and mechanics",
                         "Game development workflow",
                         "Introduction to Unity and Unreal Engine",
                         "Game industry overview and career paths",
                    ],
               },
               {
                    week: 2,
                    title: "Unity Basics & Interface",
                    topics: [
                         "Unity interface and workspace setup",
                         "Game objects and components",
                         "Scene management and organization",
                         "Basic scripting with C#",
                    ],
               },
               {
                    week: 3,
                    title: "Game Programming Fundamentals",
                    topics: [
                         "C# programming for games",
                         "Variables, functions, and classes",
                         "Game loops and update cycles",
                         "Input handling and controls",
                    ],
               },
               {
                    week: 4,
                    title: "3D Graphics & Modeling",
                    topics: [
                         "3D modeling basics with Blender",
                         "Texturing and materials",
                         "Lighting and rendering",
                         "Asset optimization and performance",
                    ],
               },
               {
                    week: 5,
                    title: "Game Physics & Animation",
                    topics: [
                         "Physics engines and rigid bodies",
                         "Collision detection and response",
                         "Character animation systems",
                         "Particle effects and visual feedback",
                    ],
               },
               {
                    week: 6,
                    title: "User Interface & UX",
                    topics: [
                         "UI design principles for games",
                         "Canvas and UI components",
                         "Menu systems and navigation",
                         "User experience optimization",
                    ],
               },
               {
                    week: 7,
                    title: "Audio & Sound Design",
                    topics: [
                         "Audio implementation in games",
                         "Sound effects and music integration",
                         "3D audio and spatial sound",
                         "Audio optimization and compression",
                    ],
               },
               {
                    week: 8,
                    title: "Game AI & Behavior",
                    topics: [
                         "Artificial intelligence in games",
                         "Pathfinding and navigation",
                         "Behavior trees and state machines",
                         "NPC and enemy AI systems",
                    ],
               },
               {
                    week: 9,
                    title: "Multiplayer & Networking",
                    topics: [
                         "Multiplayer game architecture",
                         "Client-server communication",
                         "Synchronization and lag compensation",
                         "Online game services integration",
                    ],
               },
               {
                    week: 10,
                    title: "Mobile Game Development",
                    topics: [
                         "Mobile-specific considerations",
                         "Touch controls and gestures",
                         "Performance optimization for mobile",
                         "App store deployment and monetization",
                    ],
               },
               {
                    week: 11,
                    title: "Game Testing & Quality Assurance",
                    topics: [
                         "Game testing methodologies",
                         "Bug tracking and reporting",
                         "Performance profiling and optimization",
                         "User testing and feedback integration",
                    ],
               },
               {
                    week: 12,
                    title: "Game Deployment & Marketing",
                    topics: [
                         "Game packaging and distribution",
                         "Platform-specific requirements",
                         "Marketing strategies for games",
                         "Post-launch support and updates",
                    ],
               },
          ],
          prerequisites: [
               "Basic programming knowledge (C# preferred)",
               "Understanding of 3D graphics concepts",
               "Creative thinking and problem-solving skills",
               "Organizational commitment to game development",
          ],
          outcomes: [
               "Develop complete games from concept to deployment",
               "Master Unity and Unreal Engine development",
               "Create engaging interactive experiences",
               "Implement game mechanics and systems",
               "Build multiplayer and mobile games",
               "Deploy games to multiple platforms",
          ],
          targetOrganizations: [
               "Gaming Companies",
               "Educational Institutions",
               "Entertainment Studios",
               "Technology Companies",
          ],
          deliveryOptions: [
               "In-Person Training",
               "Online Sessions",
               "Hybrid Approach",
               "Custom Schedule",
          ],
     },
     "mobile-app-development": {
          id: 7,
          title: "Mobile App Development & Cross-Platform Solutions",
          description:
               "Comprehensive training program for organizations to build native and cross-platform mobile applications using React Native, Flutter, and modern mobile development practices.",
          longDescription:
               "This intensive mobile app development training program covers both native and cross-platform development approaches. Organizations will learn to create high-performance mobile applications for iOS and Android using React Native, Flutter, and native development tools. Perfect for teams looking to establish mobile presence or develop internal mobile solutions.",
          duration: "10 weeks",
          level: "Beginner to Intermediate",
          price: "Custom Pricing",
          originalPrice: null,
          rating: 4.8,
          organizationsServed: 35,
          image: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=80",
          category: "Mobile Development",
          organizationType: "All Organizations",
          participants: "12-25 professionals",
          format: "Hybrid (Online + In-Person)",
          instructor: {
               name: "Vaskar Parajuli",
               bio: "Mobile Development Expert and Technical Lead with 10+ years of experience in iOS, Android, and cross-platform mobile development.",
               image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=150&q=80",
          },
          features: [
               "10 weeks of comprehensive mobile development training",
               "React Native and Flutter mastery",
               "Native iOS and Android development",
               "Mobile UI/UX design principles",
               "Certificate of completion",
               "Post-training mobile development consultation",
               "Flexible scheduling options",
               "Real-world mobile app projects",
          ],
          curriculum: [
               {
                    week: 1,
                    title: "Mobile Development Fundamentals",
                    topics: [
                         "Mobile app ecosystem overview",
                         "iOS and Android platform differences",
                         "Mobile development tools and environments",
                         "App store guidelines and requirements",
                    ],
               },
               {
                    week: 2,
                    title: "React Native Basics",
                    topics: [
                         "React Native setup and configuration",
                         "Components and JSX syntax",
                         "State management with hooks",
                         "Navigation and routing",
                    ],
               },
               {
                    week: 3,
                    title: "Flutter Development",
                    topics: [
                         "Flutter framework and Dart language",
                         "Widgets and material design",
                         "State management with Provider/Bloc",
                         "Custom widgets and animations",
                    ],
               },
               {
                    week: 4,
                    title: "Mobile UI/UX Design",
                    topics: [
                         "Mobile design principles and patterns",
                         "Responsive design for mobile",
                         "Accessibility and inclusive design",
                         "Design systems and component libraries",
                    ],
               },
               {
                    week: 5,
                    title: "Native iOS Development",
                    topics: [
                         "Swift programming language",
                         "iOS app architecture (MVC, MVVM)",
                         "UIKit and SwiftUI frameworks",
                         "iOS app lifecycle and memory management",
                    ],
               },
               {
                    week: 6,
                    title: "Native Android Development",
                    topics: [
                         "Kotlin programming language",
                         "Android app architecture (MVVM, Clean Architecture)",
                         "Android UI components and layouts",
                         "Android app lifecycle and services",
                    ],
               },
               {
                    week: 7,
                    title: "Mobile Backend Integration",
                    topics: [
                         "RESTful API integration",
                         "Authentication and authorization",
                         "Data persistence and caching",
                         "Push notifications implementation",
                    ],
               },
               {
                    week: 8,
                    title: "Advanced Mobile Features",
                    topics: [
                         "Camera and media integration",
                         "Location services and maps",
                         "Biometric authentication",
                         "Offline functionality and sync",
                    ],
               },
               {
                    week: 9,
                    title: "Mobile Testing & Deployment",
                    topics: [
                         "Mobile app testing strategies",
                         "Unit testing and integration testing",
                         "App store submission process",
                         "CI/CD for mobile applications",
                    ],
               },
               {
                    week: 10,
                    title: "Performance & Optimization",
                    topics: [
                         "Mobile app performance optimization",
                         "Memory management and profiling",
                         "Battery optimization techniques",
                         "App store optimization (ASO)",
                    ],
               },
          ],
          prerequisites: [
               "Basic programming knowledge (JavaScript/TypeScript)",
               "Understanding of web development concepts",
               "Familiarity with mobile devices and platforms",
               "Organizational commitment to mobile development",
          ],
          outcomes: [
               "Build native and cross-platform mobile applications",
               "Master React Native and Flutter development",
               "Create responsive and accessible mobile UIs",
               "Implement mobile-specific features and integrations",
               "Deploy apps to iOS and Android app stores",
               "Optimize mobile app performance and user experience",
          ],
          targetOrganizations: [
               "Technology Companies",
               "Startups",
               "Enterprises",
               "Digital Agencies",
          ],
          deliveryOptions: [
               "In-Person Training",
               "Online Sessions",
               "Hybrid Approach",
               "Custom Schedule",
          ],
     },
};

// Helper function to get all training programs as an array
export const getAllTrainingPrograms = () => {
     return Object.entries(trainingProgramsData).map(([slug, program]) => ({
          ...program,
          slug,
     }));
};

// Helper function to get featured training programs (first 3)
export const getFeaturedTrainingPrograms = () => {
     return getAllTrainingPrograms().slice(0, 3);
};

// Helper function to get training program by slug
export const getTrainingProgramBySlug = (slug: string) => {
     return trainingProgramsData[slug as keyof typeof trainingProgramsData];
};
